module.exports = {
  plugins: [require('daisyui'), require('tailwind-scrollbar-hide')],
  variants: {
    extend: {
      opacity: ['disabled'],
      cursor: ['disabled'],
    },
  },
  theme: {
    fontFamily: {
      sans: ['Poppins', 'sans-serif'],
      serif: ['Merriweather', 'serif'],
    },
  },
  daisyui: {
    themes: [
      {
        light: {
          primary: '#29848e',
          secondary: '#5c8bc4',
          accent: '#f4ad66',
          neutral: '#1C262C',
          'base-100': '#E6E6EA',
          info: '#77A0F8',
          success: '#1CA65A',
          warning: '#EEAB68',
          error: '#ED615E',
        },
        dark: {
          primary: '#29848e',
          secondary: '#5c8bc4',
          accent: '#f4ad66',
          neutral: '#1C262C',
          'base-100': '#2a303c',
          info: '#77A0F8',
          success: '#1CA65A',
          warning: '#EEAB68',
          error: '#ED615E',
        },
      },
      'cupcake',
      'bumblebee',
      'emerald',
      'corporate',
      'synthwave',
      'retro',
      'cyberpunk',
      'valentine',
      'halloween',
      'garden',
      'forest',
      'aqua',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'black',
      'luxury',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'acid',
      'lemonade',
      'night',
      'coffee',
      'winter',
    ],
  },
};
